sudo: false
language: python

# note that travis still builds PRs so that covers
# other branches
branches:
  only:
    - master

python:
    - "2.7"

before_install:
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install fakeredis # needed for tests
  - pip install .

script:
  - PYTHONPATH=. trial tests
